---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-sample
spec:
  containers:
    - name: nginx-container
      image: nginx:1.25.3
      volumeMounts:
        - name: secret-secret
          mountPath: /etc/config
  volumes:
    - name: secret-secret
      secret:
        secretName: nginx-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  server.key: ZU05a3UzZWNDcFVMOXpQb0lJdUcycHRaWkM1Q3U0WkNRWFJ5bWxIYWpZdlp5ZmZwTTYK
